### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by Mamelukki** [hisahi/Nanibgal#1]
Projekti ladattu sunnuntaina 7.10. klo 12.30.

Ensivaikutelma oli varsin hyvä. Sovelluksesi näyttää ammattimaiselta - olet käyttänyt hienosti html-elementtejä, projektissasi on paljon tietokantoja ja niiden välisiä yhteyksiä ja sovelluksessa on paljon hyödyllisiä toimintoja. Mahtavaa, että sovellusta voi käyttää sekä englanniksi että suomeksi.

Sovelluksen kansiorakenne on hyvin erilainen kuin kurssimateriaalissa, missä ei sinänsä ole mitään vikaa. Sovelluksen tutkiminen olisi ehkä käynyt helpommin, jos aina yhteen kokonaisuuteen liittyvät tiedostot olisivat olleet samassa kansiossa. Nyt esim. kaikki html-sivut ovat kyllä saman kansion alla, mutta niitä on paljon, joten kokonaisuuden hahmottaminen voisi olla helpompaa selkeämmällä ja yksityiskohtaisemmalla kansiorakenteella.

Sovelluksen käytettävyyttä voisi vielä parantaa. Esimerkiksi haku toimii hyvin, mutta on ehkä vähän epälooginen. Voisiko käyttäjähaku ja viestihaku olla selkeästi omilla sivuillaan, eikä niin, että käyttäjähaun linkki löytyy viestihaun alta? Tai voisiko esimerkiksi haku-linkin alla olla valinta koskien sitä, mitä käyttäjä haluaa hakea ja valinnan mukaan sovellus ohjaa sitten joko viesti- tai käyttäjähakuun?

Aloitussivua voisi ehkä myös miettiä. Kirjautumissivu sinällään on ok aloitussivuna (etenkin jos kaikki sovelluksen toiminnot vaativat kirjautumisen), mutta rekisteröitymiseen voisi olla sujuvampi yhteys. Sovelluksessa voisi olla esimerkiksi selkeämpi linkki rekisteröitymissivuun, jotta sen huomaa heti eikä sitä joudu etsimään kirjautumissivun pohjalta.

Viestit toimivat hyvin. Tuli vielä mieleen, että jos johonkin viestiin vastaa ja sen jälkeen alkuperäisen viestin poistaa, vastaukset jäävät silti elämään. En tiedä, onko tämä välttämättä huono asia,  mutta käyttäjän kannalta on vähän hassua nähdä pelkät vastaukset, mutta ei sitä, mihin vastataan.

En löytänyt repositoriostasi valmista testikäyttäjää (mikä voisi olla kätevä sovelluksen testaamiseen), mutta tein itse uuden. En päässyt testaamaan muita kuin normaalikäyttäjän oikeuksia, joten valvojan user storyjen toimivuudesta en osaa sanoa mitään. Kaikki muut user storyt mielestäni toimivat paitsi käyttäjän seuraaminen. Loin siis kaksi käyttäjää ja yritin seurata toista käyttäjää, mutta follow-toiminto aiheuttaakin internal server errorin. Tällöin myöskään feedissä en saa mitään muuta näkyviin kuin itseni lähettämät viestit. Tämä lienee hyvä korjata seuraavaksi?

Projektissasi on paljon koodia, josta iso osa on sellaista, mitä en oikein ymmärrä ja sen läpikäyminen ajatuksella veisi turhan paljon aikaa. Yleisilme on kuitenkin hyvä: metodien ym. nimeäminen on järkevää ja näyttää omaan silmääni asianmukaiselta.  Olet myös saanut paljon aikaan todella lyhyessä ajassa ja korjattavaakin löytyi vain hieman, hyvää työtä.

**Comment by hisahi** [comment]
Kiitos palautteestasi.

* Tulen selkeyttämään HTML-sivujen kansiorakennetta.
* Haun osalta saatan yksinkertaisesti yhdistää käyttäjä- ja viestihaun lomakkeet niin, että ne ovat samalla sivulla selkeästi otsikoilla erotettuina.
* Vastausten jääminen alkuperäisen viestinkin poistuessa on tietääkseni mikroblogipalveluissa normaalia.
* Rekisteröitymislinkin osalta sellainen voidaan lisätä yläoikeaan laitaan.
* Valvojakäyttäjän luominen onnistuu luomalla normaali käyttäjä ja sitten muokkaamalla tätä tietokannasta asettamalla is_admin olemaan tosi.
* Seuraamisen ei tosiaan pitäisi tuottaa internal server erroria.
